/**
 * DeepAffects
 * OpenAPI Specification of DeepAffects APIs
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DeepAffects) {
      root.DeepAffects = {};
    }
    root.DeepAffects.AsyncResponse = factory(root.DeepAffects.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AsyncResponse model module.
   * @module model/AsyncResponse
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>AsyncResponse</code>.
   * @alias module:model/AsyncResponse
   * @class
   * @param requestId {String} Unique identifier for the api call
   * @param api {String} API hit
   */
  var exports = function(requestId, api) {
    var _this = this;

    _this['request_id'] = requestId;
    _this['api'] = api;
  };

  /**
   * Constructs a <code>AsyncResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AsyncResponse} obj Optional instance to populate.
   * @return {module:model/AsyncResponse} The populated <code>AsyncResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('request_id')) {
        obj['request_id'] = ApiClient.convertToType(data['request_id'], 'String');
      }
      if (data.hasOwnProperty('api')) {
        obj['api'] = ApiClient.convertToType(data['api'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique identifier for the api call
   * @member {String} request_id
   */
  exports.prototype['request_id'] = undefined;
  /**
   * API hit
   * @member {String} api
   */
  exports.prototype['api'] = undefined;



  return exports;
}));


