/**
 * DeepAffects
 * OpenAPI Specification of DeepAffects APIs
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
var fs = require('fs');
var is = require('is');
var path = require('path');
var utils = require('./utils');

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DeepAffects) {
      root.DeepAffects = {};
    }
    root.DeepAffects.Audio = factory(root.DeepAffects.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Audio model module.
   * @module model/Audio
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Audio</code>.
   * @alias module:model/Audio
   * @class
   * @param encoding {String} Encoding of audio file like MP3, WAV etc.
   * @param sampleRate {Number} Sample rate of the audio file.
   * @param languageCode {String} Language spoken in the audio file.
   * @param content {String} base64 encoding of the audio file.
   */
  var exports = function(encoding, sampleRate, languageCode, content) {
    var _this = this;

    _this['encoding'] = encoding;
    _this['sampleRate'] = sampleRate;
    _this['languageCode'] = languageCode;
    _this['content'] = content;
  };

  /**
   * Constructs a <code>Audio</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Audio} obj Optional instance to populate.
   * @return {module:model/Audio} The populated <code>Audio</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('encoding')) {
        obj['encoding'] = ApiClient.convertToType(data['encoding'], 'String');
      }
      if (data.hasOwnProperty('sampleRate')) {
        obj['sampleRate'] = ApiClient.convertToType(data['sampleRate'], 'Number');
      }
      if (data.hasOwnProperty('languageCode')) {
        obj['languageCode'] = ApiClient.convertToType(data['languageCode'], 'String');
      }
      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], 'String');
      }
    }
    return obj;
  }

  exports.fromFile = function(file, encoding, sampleRate, languageCode) {
    var exp = new exports();
    exp['encoding'] = encoding || utils.detectEncoding(file);
    exp['sampleRate'] = utils.defaultFor(sampleRate, 8000);
    exp['languageCode'] = utils.defaultFor(languageCode, 'en-US');
    exp['content'] = utils.findFile(file).toString('base64');
    return exp;
  }

  /**
   * Encoding of audio file like MP3, WAV etc.
   * @member {String} encoding
   */
  exports.prototype['encoding'] = undefined;
  /**
   * Sample rate of the audio file.
   * @member {Number} sampleRate
   */
  exports.prototype['sampleRate'] = undefined;
  /**
   * Language spoken in the audio file.
   * @member {String} languageCode
   * @default 'en-US'
   */
  exports.prototype['languageCode'] = 'en-US';
  /**
   * base64 encoding of the audio file.
   * @member {String} content
   */
  exports.prototype['content'] = undefined;



  return exports;
}));
