/**
 * SeerNet Audio APIs
 * OpenAPI Specification of SeerNet audio APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SeerNetAudioApIs);
  }
}(this, function(expect, SeerNetAudioApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SeerNetAudioApIs.AsyncResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AsyncResponse', function() {
    it('should create an instance of AsyncResponse', function() {
      // uncomment below and update the code to test AsyncResponse
      //var instane = new SeerNetAudioApIs.AsyncResponse();
      //expect(instance).to.be.a(SeerNetAudioApIs.AsyncResponse);
    });

    it('should have the property requestId (base name: "request_id")', function() {
      // uncomment below and update the code to test the property requestId
      //var instane = new SeerNetAudioApIs.AsyncResponse();
      //expect(instance).to.be();
    });

    it('should have the property api (base name: "api")', function() {
      // uncomment below and update the code to test the property api
      //var instane = new SeerNetAudioApIs.AsyncResponse();
      //expect(instance).to.be();
    });

  });

}));
