/**
 * DeepAffects
 * OpenAPI Specification of DeepAffects APIs
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AsyncResponse', 'model/Audio', 'model/DiarizeAudio', 'model/EmotionScore', 'api/DenoiseApi', 'api/DiarizeApi', 'api/DiarizeApiV2', 'api/EllipsisApi', 'api/EmotionApi', 'api/FeaturizeApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AsyncResponse'), require('./model/Audio'), require('./model/DiarizeAudio'), require('./model/EmotionScore'), require('./api/DenoiseApi'), require('./api/DiarizeApi'), require('./api/DiarizeApiV2'), require('./api/EllipsisApi'), require('./api/EmotionApi'), require('./api/FeaturizeApi'));
  }
}(function(ApiClient, AsyncResponse, Audio, DiarizeAudio, EmotionScore, DenoiseApi, DiarizeApi, DiarizeApiV2, EllipsisApi, EmotionApi, FeaturizeApi) {
  'use strict';

  /**
   * OpenAPI_Specification_of_DeepAffects_APIs.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var DeepAffects = require('index'); // See note below*.
   * var xxxSvc = new DeepAffects.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new DeepAffects.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new DeepAffects.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new DeepAffects.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AsyncResponse model constructor.
     * @property {module:model/AsyncResponse}
     */
    AsyncResponse: AsyncResponse,
    /**
     * The Audio model constructor.
     * @property {module:model/Audio}
     */
    Audio: Audio,
    /**
     * The DiarizeAudio model constructor.
     * @property {module:model/DiarizeAudio}
     */
    DiarizeAudio: DiarizeAudio,
    /**
     * The EmotionScore model constructor.
     * @property {module:model/EmotionScore}
     */
    EmotionScore: EmotionScore,
    /**
     * The DenoiseApi service constructor.
     * @property {module:api/DenoiseApi}
     */
    DenoiseApi: DenoiseApi,
    /**
     * The DiarizeApi service constructor.
     * @property {module:api/DiarizeApi}
     */
    DiarizeApi: DiarizeApi,
    /**
     * The DiarizeApiV2 service constructor.
     * @property {module:api/DiarizeApiV2}
     */
    DiarizeApiV2: DiarizeApiV2,
    /**
     * The EllipsisApi service constructor.
     * @property {module:api/EllipsisApi}
     */
    EllipsisApi: EllipsisApi,
    /**
     * The EmotionApi service constructor.
     * @property {module:api/EmotionApi}
     */
    EmotionApi: EmotionApi,
    /**
     * The FeaturizeApi service constructor.
     * @property {module:api/FeaturizeApi}
     */
    FeaturizeApi: FeaturizeApi
  };

  return exports;
}));
